site_name: Udviklingsmilj√∏er - GitHub Pages
site_description: Documentation for our awesome team
site_author: Your Name
theme:
 name: material

extra_css:
 - css/main.css

nav:
 - Forside: index.md
 - End to End testing: e2etest.md
 - Versionsstyring: github.md
 - Statisk kode analyse: staticcodeanalysis.md
 - Unitest: unitest.md

